// lib/mock-craftsmen.ts

export interface Craftsman {
  id: string;
  name: string;
  businessName: string;
  image: string | null;
  verificationLevel: "REGISTERED" | "VERIFIED" | "APPROVED";
  rating: number;
  reviewCount: number;
  category: string; // Parent Category
  subServices: string[]; // Sub-services per the Prisma schema
  region: string;
  priceMin: number;
  priceMax: number;
  jobsCompleted: number;
}

export const allCraftsmen: Craftsman[] = [
  {
    id: "craftsman-1",
    name: "Ahmet Yılmaz",
    businessName: "Yılmaz Plumbing",
    image: null,
    verificationLevel: "APPROVED" as const,
    rating: 4.9,
    reviewCount: 18,
    category: "Plumbing & Water Systems",
    subServices: ["Pipe Installation", "Water Heater Repair", "Drain Cleaning"],
    region: "Nicosia",
    priceMin: 150,
    priceMax: 450,
    jobsCompleted: 47,
  },
  {
    id: "craftsman-2",
    name: "Mehmet Demir",
    businessName: "Demir Electrical",
    image: null,
    verificationLevel: "VERIFIED" as const,
    rating: 4.8,
    reviewCount: 22,
    category: "Electrical",
    subServices: ["Wiring & Lighting", "Panel Upgrades", "Home Automation"],
    region: "Kyrenia",
    priceMin: 200,
    priceMax: 600,
    jobsCompleted: 38,
  },
  {
    id: "craftsman-3",
    name: "Ayşe Kaya",
    businessName: "Kaya Painting & Decor",
    image: null,
    verificationLevel: "REGISTERED" as const,
    rating: 4.7,
    reviewCount: 9,
    category: "Painting & Plastering",
    subServices: ["Interior Painting", "Drywall & Plaster"],
    region: "Famagusta",
    priceMin: 100,
    priceMax: 350,
    jobsCompleted: 24,
  },
  {
    id: "craftsman-4",
    name: "Mustafa Çelik",
    businessName: "Çelik Woodworks",
    image: null,
    verificationLevel: "VERIFIED" as const,
    rating: 4.9,
    reviewCount: 15,
    category: "Carpentry & Furniture",
    subServices: ["Custom Furniture", "Door Installation", "Flooring"],
    region: "Larnaca",
    priceMin: 300,
    priceMax: 1200,
    jobsCompleted: 32,
  },
  {
    id: "craftsman-5",
    name: "Zeynep Öztürk",
    businessName: "Öztürk Garden & Pool",
    image: null,
    verificationLevel: "REGISTERED" as const,
    rating: 4.6,
    reviewCount: 7,
    category: "Garden & Pool Maintenance",
    subServices: ["Landscaping", "Pool Cleaning", "Irrigation"],
    region: "Morphou",
    priceMin: 180,
    priceMax: 500,
    jobsCompleted: 19,
  },
  {
    id: "craftsman-6",
    name: "Ali Can",
    businessName: "Can Heating & Cooling",
    image: null,
    verificationLevel: "VERIFIED" as const,
    rating: 4.7,
    reviewCount: 12,
    category: "HVAC & Refrigeration",
    subServices: ["AC Installation", "AC Repair", "Ventilation"],
    region: "Nicosia",
    priceMin: 250,
    priceMax: 800,
    jobsCompleted: 28,
  },
  {
    id: "craftsman-7",
    name: "Elif Yıldız",
    businessName: "Yıldız Electronics Repair",
    image: null,
    verificationLevel: "REGISTERED" as const,
    rating: 4.5,
    reviewCount: 5,
    category: "Appliance & Electronics Repair",
    subServices: ["Washing Machine Repair", "TV Repair"],
    region: "Kyrenia",
    priceMin: 80,
    priceMax: 250,
    jobsCompleted: 15,
  },
  {
    id: "craftsman-8",
    name: "Hasan Eminağa",
    businessName: "Eminağa Furniture",
    image: null,
    verificationLevel: "APPROVED" as const,
    rating: 4.8,
    reviewCount: 21,
    category: "Carpentry & Furniture",
    subServices: ["Custom Furniture", "Door Installation"],
    region: "Famagusta",
    priceMin: 400,
    priceMax: 1500,
    jobsCompleted: 44,
  },
  {
    id: "craftsman-9",
    name: "Fatma Şahin",
    businessName: "Şahin Glass & Aluminium",
    image: null,
    verificationLevel: "REGISTERED" as const,
    rating: 4.4,
    reviewCount: 4,
    category: "Aluminium, PVC & Glass",
    subServices: ["Window Installation", "Door Frames", "Glass Repair"],
    region: "Larnaca",
    priceMin: 150,
    priceMax: 450,
    jobsCompleted: 11,
  },
  {
    id: "craftsman-10",
    name: "Kemal Aydın",
    businessName: "Aydın Painting",
    image: null,
    verificationLevel: "VERIFIED" as const,
    rating: 4.6,
    reviewCount: 13,
    category: "Painting & Plastering",
    subServices: ["Exterior Painting", "Drywall & Plaster"],
    region: "Morphou",
    priceMin: 120,
    priceMax: 380,
    jobsCompleted: 29,
  },
  {
    id: "craftsman-11",
    name: "Hatice Yılmaz",
    businessName: "Yılmaz Electric",
    image: null,
    verificationLevel: "REGISTERED" as const,
    rating: 4.3,
    reviewCount: 6,
    category: "Electrical",
    subServices: ["Wiring & Lighting", "Panel Upgrades"],
    region: "Nicosia",
    priceMin: 180,
    priceMax: 550,
    jobsCompleted: 16,
  },
  {
    id: "craftsman-12",
    name: "Serkan Kaya",
    businessName: "Kaya Plumbing",
    image: null,
    verificationLevel: "VERIFIED" as const,
    rating: 4.7,
    reviewCount: 10,
    category: "Plumbing & Water Systems",
    subServices: ["Pipe Installation", "Water Heater Repair"],
    region: "Kyrenia",
    priceMin: 140,
    priceMax: 420,
    jobsCompleted: 22,
  },
  {
    id: "craftsman-13",
    name: "Merve Demir",
    businessName: "Demir Climate",
    image: null,
    verificationLevel: "REGISTERED" as const,
    rating: 4.5,
    reviewCount: 8,
    category: "HVAC & Refrigeration",
    subServices: ["AC Repair", "Ventilation"],
    region: "Famagusta",
    priceMin: 220,
    priceMax: 700,
    jobsCompleted: 18,
  },
  {
    id: "craftsman-14",
    name: "Okan Çelik",
    businessName: "Çelik Outdoor Services",
    image: null,
    verificationLevel: "VERIFIED" as const,
    rating: 4.6,
    reviewCount: 11,
    category: "Garden & Pool Maintenance",
    subServices: ["Landscaping", "Irrigation"],
    region: "Larnaca",
    priceMin: 160,
    priceMax: 480,
    jobsCompleted: 25,
  },
  {
    id: "craftsman-15",
    name: "Seda Öztürk",
    businessName: "Öztürk Glass",
    image: null,
    verificationLevel: "REGISTERED" as const,
    rating: 4.2,
    reviewCount: 3,
    category: "Aluminium, PVC & Glass",
    subServices: ["Window Installation", "Glass Repair"],
    region: "Morphou",
    priceMin: 130,
    priceMax: 400,
    jobsCompleted: 9,
  },
  {
    id: "craftsman-16",
    name: "Emre Can",
    businessName: "Can Custom Wood",
    image: null,
    verificationLevel: "APPROVED" as const,
    rating: 4.9,
    reviewCount: 17,
    category: "Carpentry & Furniture",
    subServices: ["Custom Furniture", "Flooring"],
    region: "Nicosia",
    priceMin: 350,
    priceMax: 1800,
    jobsCompleted: 41,
  },
  {
    id: "craftsman-17",
    name: "Simge Yıldız",
    businessName: "Yıldız Plastering",
    image: null,
    verificationLevel: "VERIFIED" as const,
    rating: 4.5,
    reviewCount: 9,
    category: "Painting & Plastering",
    subServices: ["Interior Painting", "Exterior Painting"],
    region: "Kyrenia",
    priceMin: 110,
    priceMax: 320,
    jobsCompleted: 20,
  },
  {
    id: "craftsman-18",
    name: "Burak Eminağa",
    businessName: "Eminağa Electric",
    image: null,
    verificationLevel: "REGISTERED" as const,
    rating: 4.4,
    reviewCount: 5,
    category: "Electrical",
    subServices: ["Home Automation", "Panel Upgrades"],
    region: "Famagusta",
    priceMin: 190,
    priceMax: 580,
    jobsCompleted: 14,
  },
  {
    id: "craftsman-19",
    name: "Cansu Şahin",
    businessName: "Şahin Appliance Repair",
    image: null,
    verificationLevel: "VERIFIED" as const,
    rating: 4.7,
    reviewCount: 14,
    category: "Appliance & Electronics Repair",
    subServices: ["Fridge Repair", "Washing Machine Repair"],
    region: "Larnaca",
    priceMin: 90,
    priceMax: 280,
    jobsCompleted: 27,
  },
  {
    id: "craftsman-20",
    name: "Murat Aydın",
    businessName: "Aydın Water Systems",
    image: null,
    verificationLevel: "REGISTERED" as const,
    rating: 4.3,
    reviewCount: 6,
    category: "Plumbing & Water Systems",
    subServices: ["Pipe Installation", "Drain Cleaning"],
    region: "Morphou",
    priceMin: 160,
    priceMax: 480,
    jobsCompleted: 13,
  },
];